var searchData=
[
  ['platform_0',['platform',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md17',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_2&quot;&gt;&lt;/a&gt; 2.2. GLM_FORCE_PLATFORM_UNKNOWN: Force GLM to no detect the build platform'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md556',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_2&quot;&gt;&lt;/a&gt; 2.2. GLM_FORCE_PLATFORM_UNKNOWN: Force GLM to no detect the build platform']]],
  ['platform_20auto_20detection_20and_20default_20configuration_1',['Platform auto detection and default configuration',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md16',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_1&quot;&gt;&lt;/a&gt; 2.1. GLM_FORCE_MESSAGES: Platform auto detection and default configuration'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md555',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_1&quot;&gt;&lt;/a&gt; 2.1. GLM_FORCE_MESSAGES: Platform auto detection and default configuration']]],
  ['point_20types_2',['point types',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md28',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_13&quot;&gt;&lt;/a&gt; 2.13. GLM_FORCE_SINGLE_ONLY: Removed explicit 64-bits floating point types'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md567',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_13&quot;&gt;&lt;/a&gt; 2.13. GLM_FORCE_SINGLE_ONLY: Removed explicit 64-bits floating point types']]],
  ['precision_3',['precision',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md27',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_12&quot;&gt;&lt;/a&gt; 2.12. GLM_FORCE_PRECISION_**: Default precision'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md566',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_12&quot;&gt;&lt;/a&gt; 2.12. GLM_FORCE_PRECISION_**: Default precision']]],
  ['precision_20qualifiers_4',['precision qualifiers',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md129',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_10&quot;&gt;&lt;/a&gt; 3.10. Quaternion types with precision qualifiers'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md668',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_10&quot;&gt;&lt;/a&gt; 3.10. Quaternion types with precision qualifiers'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md70',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_4&quot;&gt;&lt;/a&gt; 3.4. Vector types with precision qualifiers'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md609',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_4&quot;&gt;&lt;/a&gt; 3.4. Vector types with precision qualifiers'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md102',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_7&quot;&gt;&lt;/a&gt; 3.7. Matrix types with precision qualifiers'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md641',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_7&quot;&gt;&lt;/a&gt; 3.7. Matrix types with precision qualifiers']]],
  ['precision_20qualifiers_20support_5',['Precision qualifiers support',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md168',1,'&lt;a class=&quot;anchor&quot; id=&quot;section6_2&quot;&gt;&lt;/a&gt; 6.2. Precision qualifiers support'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md707',1,'&lt;a class=&quot;anchor&quot; id=&quot;section6_2&quot;&gt;&lt;/a&gt; 6.2. Precision qualifiers support']]],
  ['preprocessor_20configurations_6',['Preprocessor configurations',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md15',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2&quot;&gt;&lt;/a&gt; 2. Preprocessor configurations'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md554',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2&quot;&gt;&lt;/a&gt; 2. Preprocessor configurations']]],
  ['program_7',['program',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md172',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_2&quot;&gt;&lt;/a&gt; 7.2. Does GLM run GLSL program?'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md711',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_2&quot;&gt;&lt;/a&gt; 7.2. Does GLM run GLSL program?']]],
  ['project_20health_8',['Project Health',['../dir_06717e3f51fda062a103301b6d3ab099.html#autotoc_md214',1,'Project Health'],['../dir_773be3d019cbbaf59b5bd6860ea7a51d.html#autotoc_md753',1,'Project Health']]],
  ['projects_20using_20glm_9',['Projects using GLM',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md208',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10_3&quot;&gt;&lt;/a&gt; 10.3. Projects using GLM'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md747',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10_3&quot;&gt;&lt;/a&gt; 10.3. Projects using GLM']]],
  ['pull_20request_10',['Pull Request',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md197',1,'Step 4: Submitting a Pull Request'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md736',1,'Step 4: Submitting a Pull Request']]],
  ['pull_20request_11',['pull request',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md193',1,'&lt;a class=&quot;anchor&quot; id=&quot;section9_2&quot;&gt;&lt;/a&gt; 9.2. Contributing to GLM with pull request'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md732',1,'&lt;a class=&quot;anchor&quot; id=&quot;section9_2&quot;&gt;&lt;/a&gt; 9.2. Contributing to GLM with pull request']]]
];
