var searchData=
[
  ['recommended_20extensions_0',['Recommended extensions',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md140',1,'&lt;a class=&quot;anchor&quot; id=&quot;section4&quot;&gt;&lt;/a&gt; 4. Recommended extensions'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md679',1,'&lt;a class=&quot;anchor&quot; id=&quot;section4&quot;&gt;&lt;/a&gt; 4. Recommended extensions']]],
  ['references_1',['References',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md205',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10&quot;&gt;&lt;/a&gt; 10. References'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md744',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10&quot;&gt;&lt;/a&gt; 10. References']]],
  ['release_2',['release',['../dir_06717e3f51fda062a103301b6d3ab099.html#autotoc_md213',1,'&lt;a href=&quot;https://github.com/g-truc/glm/releases/latest&quot;&gt;Latest release&lt;/a&gt;'],['../dir_773be3d019cbbaf59b5bd6860ea7a51d.html#autotoc_md752',1,'&lt;a href=&quot;https://github.com/g-truc/glm/releases/latest&quot;&gt;Latest release&lt;/a&gt;']]],
  ['release_20notes_3',['Release notes',['../dir_06717e3f51fda062a103301b6d3ab099.html#autotoc_md218',1,'Release notes'],['../dir_773be3d019cbbaf59b5bd6860ea7a51d.html#autotoc_md757',1,'Release notes']]],
  ['removed_20explicit_2064_20bits_20floating_20point_20types_4',['Removed explicit 64 bits floating point types',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md28',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_13&quot;&gt;&lt;/a&gt; 2.13. GLM_FORCE_SINGLE_ONLY: Removed explicit 64-bits floating point types'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md567',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_13&quot;&gt;&lt;/a&gt; 2.13. GLM_FORCE_SINGLE_ONLY: Removed explicit 64-bits floating point types']]],
  ['removing_20gentype_20restriction_5',['Removing genType restriction',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md36',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_19&quot;&gt;&lt;/a&gt; 2.19. GLM_FORCE_UNRESTRICTED_GENTYPE: Removing genType restriction'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md575',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_19&quot;&gt;&lt;/a&gt; 2.19. GLM_FORCE_UNRESTRICTED_GENTYPE: Removing genType restriction']]],
  ['renderer3dds_6',['Renderer3DDS',['../C:/Users/User/Desktop/Projects/MultiStation/README.md#autotoc_md524',1,'']]],
  ['replacements_20for_20deprecated_20opengl_20functions_7',['replacements for deprecated OpenGL functions',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md163',1,'&lt;a class=&quot;anchor&quot; id=&quot;section5_1&quot;&gt;&lt;/a&gt; 5.1. GLM replacements for deprecated OpenGL functions'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md702',1,'&lt;a class=&quot;anchor&quot; id=&quot;section5_1&quot;&gt;&lt;/a&gt; 5.1. GLM replacements for deprecated OpenGL functions']]],
  ['replacements_20for_20glu_20functions_8',['replacements for GLU functions',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md164',1,'&lt;a class=&quot;anchor&quot; id=&quot;section5_2&quot;&gt;&lt;/a&gt; 5.2. GLM replacements for GLU functions'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md703',1,'&lt;a class=&quot;anchor&quot; id=&quot;section5_2&quot;&gt;&lt;/a&gt; 5.2. GLM replacements for GLU functions']]],
  ['reports_9',['reports',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md192',1,'&lt;a class=&quot;anchor&quot; id=&quot;section9_1&quot;&gt;&lt;/a&gt; 9.1. Submitting bug reports'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md731',1,'&lt;a class=&quot;anchor&quot; id=&quot;section9_1&quot;&gt;&lt;/a&gt; 9.1. Submitting bug reports']]],
  ['request_10',['Request',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md197',1,'Step 4: Submitting a Pull Request'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md736',1,'Step 4: Submitting a Pull Request']]],
  ['request_11',['request',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md193',1,'&lt;a class=&quot;anchor&quot; id=&quot;section9_2&quot;&gt;&lt;/a&gt; 9.2. Contributing to GLM with pull request'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md732',1,'&lt;a class=&quot;anchor&quot; id=&quot;section9_2&quot;&gt;&lt;/a&gt; 9.2. Contributing to GLM with pull request']]],
  ['requiring_20explicit_20conversions_12',['Requiring explicit conversions',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md22',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_7&quot;&gt;&lt;/a&gt; 2.7. GLM_FORCE_EXPLICIT_CTOR: Requiring explicit conversions'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md561',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_7&quot;&gt;&lt;/a&gt; 2.7. GLM_FORCE_EXPLICIT_CTOR: Requiring explicit conversions']]],
  ['restriction_13',['restriction',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md36',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_19&quot;&gt;&lt;/a&gt; 2.19. GLM_FORCE_UNRESTRICTED_GENTYPE: Removing genType restriction'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md575',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_19&quot;&gt;&lt;/a&gt; 2.19. GLM_FORCE_UNRESTRICTED_GENTYPE: Removing genType restriction']]],
  ['run_20glsl_20program_14',['run GLSL program',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md172',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_2&quot;&gt;&lt;/a&gt; 7.2. Does GLM run GLSL program?'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md711',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_2&quot;&gt;&lt;/a&gt; 7.2. Does GLM run GLSL program?']]]
];
