var searchData=
[
  ['language_20detection_0',['language detection',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md21',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_6&quot;&gt;&lt;/a&gt; 2.6. GLM_FORCE_CXX**: C++ language detection'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md560',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_6&quot;&gt;&lt;/a&gt; 2.6. GLM_FORCE_CXX**: C++ language detection']]],
  ['language_20extensions_1',['language extensions',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md31',1,'2.14.2. Swizzle operations for C++ 98 with language extensions'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md570',1,'2.14.2. Swizzle operations for C++ 98 with language extensions'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md37',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_20&quot;&gt;&lt;/a&gt; 2.20. GLM_FORCE_SILENT_WARNINGS: Silent C++ warnings from language extensions'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md576',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_20&quot;&gt;&lt;/a&gt; 2.20. GLM_FORCE_SILENT_WARNINGS: Silent C++ warnings from language extensions']]],
  ['languages_2',['languages',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md210',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10_5&quot;&gt;&lt;/a&gt; 10.5. Equivalent for other languages'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md749',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10_5&quot;&gt;&lt;/a&gt; 10.5. Equivalent for other languages']]],
  ['latest_20release_3',['Latest release',['../dir_06717e3f51fda062a103301b6d3ab099.html#autotoc_md213',1,'&lt;a href=&quot;https://github.com/g-truc/glm/releases/latest&quot;&gt;Latest release&lt;/a&gt;'],['../dir_773be3d019cbbaf59b5bd6860ea7a51d.html#autotoc_md752',1,'&lt;a href=&quot;https://github.com/g-truc/glm/releases/latest&quot;&gt;Latest release&lt;/a&gt;']]],
  ['left_20handed_20coordinate_20system_4',['left handed coordinate system',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md33',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_16&quot;&gt;&lt;/a&gt; 2.16. GLM_FORCE_LEFT_HANDED: Force left handed coordinate system'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md572',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_16&quot;&gt;&lt;/a&gt; 2.16. GLM_FORCE_LEFT_HANDED: Force left handed coordinate system']]],
  ['level_20i_20have_20warnings_5',['level I have warnings',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md179',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_9&quot;&gt;&lt;/a&gt; 7.9. When I build with Visual C++ with /W4 warning level, I have warnings...'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md718',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_9&quot;&gt;&lt;/a&gt; 7.9. When I build with Visual C++ with /W4 warning level, I have warnings...']]],
  ['library_6',['library',['../dir_7270e45dd4d220f4b9ddbf7b78700e0c.html#autotoc_md513',1,'GLFW as a static library'],['../dir_7270e45dd4d220f4b9ddbf7b78700e0c.html#autotoc_md516',1,'GLFW as a static library'],['../dir_801ab85f294ab58c499c782cdcd96633.html#autotoc_md520',1,'GLFW as a static library'],['../dir_801ab85f294ab58c499c782cdcd96633.html#autotoc_md523',1,'GLFW as a static library'],['../dir_448168ebff0167721de8987fbbdce05d.html#autotoc_md528',1,'GLFW as a static library'],['../dir_448168ebff0167721de8987fbbdce05d.html#autotoc_md531',1,'GLFW as a static library'],['../dir_c7a1a642446e7d3d6beaada17cdec169.html#autotoc_md535',1,'GLFW as a static library'],['../dir_c7a1a642446e7d3d6beaada17cdec169.html#autotoc_md538',1,'GLFW as a static library']]],
  ['license_7',['LICENSE',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_platform_2_externals_2_g_l_f_w_2_win32_2_l_i_c_e_n_s_e.html',1,'LICENSE'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_platform_2_externals_2_g_l_f_w_2x64_2_l_i_c_e_n_s_e.html',1,'LICENSE'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_f_w_2_win32_2_l_i_c_e_n_s_e.html',1,'LICENSE'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_f_w_2x64_2_l_i_c_e_n_s_e.html',1,'LICENSE']]],
  ['license_8',['License',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md5',1,'The Happy Bunny License (Modified MIT License)'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md544',1,'The Happy Bunny License (Modified MIT License)'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md6',1,'The MIT License'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md545',1,'The MIT License']]],
  ['license_20modified_20mit_20license_9',['License Modified MIT License',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md5',1,'The Happy Bunny License (Modified MIT License)'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md544',1,'The Happy Bunny License (Modified MIT License)']]],
  ['licenses_10',['Licenses',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md4',1,'&lt;a class=&quot;anchor&quot; id=&quot;section0&quot;&gt;&lt;/a&gt; Licenses'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md543',1,'&lt;a class=&quot;anchor&quot; id=&quot;section0&quot;&gt;&lt;/a&gt; Licenses']]],
  ['lighting_11',['Lighting',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md189',1,'&lt;a class=&quot;anchor&quot; id=&quot;section8_4&quot;&gt;&lt;/a&gt; 8.4. Lighting'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md728',1,'&lt;a class=&quot;anchor&quot; id=&quot;section8_4&quot;&gt;&lt;/a&gt; 8.4. Lighting']]],
  ['lines_12',['lines',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md201',1,'Blank lines'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md740',1,'Blank lines']]],
  ['links_13',['links',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md207',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10_2&quot;&gt;&lt;/a&gt; 10.2. External links'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md746',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10_2&quot;&gt;&lt;/a&gt; 10.2. External links']]],
  ['list_14',['Deprecated List',['../deprecated.html',1,'']]]
];
