var searchData=
[
  ['of_20a_20clip_20space_20between_200_20to_201_0',['of a clip space between 0 to 1',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md34',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_17&quot;&gt;&lt;/a&gt; 2.17. GLM_FORCE_DEPTH_ZERO_TO_ONE: Force the use of a clip space between 0 to 1'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md573',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_17&quot;&gt;&lt;/a&gt; 2.17. GLM_FORCE_DEPTH_ZERO_TO_ONE: Force the use of a clip space between 0 to 1']]],
  ['of_20contents_1',['of Contents',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md2',1,'Table of Contents'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md541',1,'Table of Contents']]],
  ['of_20division_20by_20zero_2',['of division by zero',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md180',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_10&quot;&gt;&lt;/a&gt; 7.10. Why some GLM functions can crash because of division by zero?'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md719',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_10&quot;&gt;&lt;/a&gt; 7.10. Why some GLM functions can crash because of division by zero?']]],
  ['of_20extensions_3',['of extensions',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md176',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_6&quot;&gt;&lt;/a&gt; 7.6. Where can I find the documentation of extensions?'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md715',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_6&quot;&gt;&lt;/a&gt; 7.6. Where can I find the documentation of extensions?']]],
  ['of_20w_20x_20y_20z_4',['of w x y z',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md38',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_21&quot;&gt;&lt;/a&gt; 2.21. GLM_FORCE_QUAT_DATA_XYZW: Force GLM to store quat data as x,y,z,w instead of w,x,y,z'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md577',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_21&quot;&gt;&lt;/a&gt; 2.21. GLM_FORCE_QUAT_DATA_XYZW: Force GLM to store quat data as x,y,z,w instead of w,x,y,z']]],
  ['only_20exposes_20x_20y_20z_20and_20w_20components_5',['Only exposes x y z and w components',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md32',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_15&quot;&gt;&lt;/a&gt; 2.15. GLM_FORCE_XYZW_ONLY: Only exposes x, y, z and w components'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md571',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_15&quot;&gt;&lt;/a&gt; 2.15. GLM_FORCE_XYZW_ONLY: Only exposes x, y, z and w components']]],
  ['opengl_20functions_6',['OpenGL functions',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md163',1,'&lt;a class=&quot;anchor&quot; id=&quot;section5_1&quot;&gt;&lt;/a&gt; 5.1. GLM replacements for deprecated OpenGL functions'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md702',1,'&lt;a class=&quot;anchor&quot; id=&quot;section5_1&quot;&gt;&lt;/a&gt; 5.1. GLM replacements for deprecated OpenGL functions']]],
  ['opengl_20interoperability_7',['OpenGL interoperability',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md162',1,'&lt;a class=&quot;anchor&quot; id=&quot;section5&quot;&gt;&lt;/a&gt; 5. OpenGL interoperability'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md701',1,'&lt;a class=&quot;anchor&quot; id=&quot;section5&quot;&gt;&lt;/a&gt; 5. OpenGL interoperability']]],
  ['opengl_20mathematics_20glm_8',['OpenGL Mathematics (GLM)',['../index.html',1,'']]],
  ['opengl_20specifications_9',['OpenGL specifications',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md206',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10_1&quot;&gt;&lt;/a&gt; 10.1. OpenGL specifications'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md745',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10_1&quot;&gt;&lt;/a&gt; 10.1. OpenGL specifications']]],
  ['operations_20for_20c_2098_20with_20language_20extensions_10',['operations for C 98 with language extensions',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md31',1,'2.14.2. Swizzle operations for C++ 98 with language extensions'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md570',1,'2.14.2. Swizzle operations for C++ 98 with language extensions']]],
  ['operators_11',['operators',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md29',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_14&quot;&gt;&lt;/a&gt; 2.14. GLM_FORCE_SWIZZLE: Enable swizzle operators'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md568',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_14&quot;&gt;&lt;/a&gt; 2.14. GLM_FORCE_SWIZZLE: Enable swizzle operators']]],
  ['optimizations_12',['optimizations',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md26',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_11&quot;&gt;&lt;/a&gt; 2.11. GLM_FORCE_INTRINSICS: Using SIMD optimizations'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md565',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_11&quot;&gt;&lt;/a&gt; 2.11. GLM_FORCE_INTRINSICS: Using SIMD optimizations']]],
  ['other_20languages_13',['other languages',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md210',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10_5&quot;&gt;&lt;/a&gt; 10.5. Equivalent for other languages'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md749',1,'&lt;a class=&quot;anchor&quot; id=&quot;section10_5&quot;&gt;&lt;/a&gt; 10.5. Equivalent for other languages']]],
  ['our_20fork_14',['our fork',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md195',1,'Step 2: Synchronizing our fork'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md734',1,'Step 2: Synchronizing our fork']]],
  ['our_20glm_20fork_15',['our GLM Fork',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md194',1,'Step 1: Setup our GLM Fork'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md733',1,'Step 1: Setup our GLM Fork'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md196',1,'Step 3: Modifying our GLM Fork'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md735',1,'Step 3: Modifying our GLM Fork']]]
];
