var searchData=
[
  ['qualifiers_0',['qualifiers',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md129',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_10&quot;&gt;&lt;/a&gt; 3.10. Quaternion types with precision qualifiers'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md668',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_10&quot;&gt;&lt;/a&gt; 3.10. Quaternion types with precision qualifiers'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md70',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_4&quot;&gt;&lt;/a&gt; 3.4. Vector types with precision qualifiers'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md609',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_4&quot;&gt;&lt;/a&gt; 3.4. Vector types with precision qualifiers'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md102',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_7&quot;&gt;&lt;/a&gt; 3.7. Matrix types with precision qualifiers'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md641',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_7&quot;&gt;&lt;/a&gt; 3.7. Matrix types with precision qualifiers']]],
  ['qualifiers_20support_1',['qualifiers support',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md168',1,'&lt;a class=&quot;anchor&quot; id=&quot;section6_2&quot;&gt;&lt;/a&gt; 6.2. Precision qualifiers support'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md707',1,'&lt;a class=&quot;anchor&quot; id=&quot;section6_2&quot;&gt;&lt;/a&gt; 6.2. Precision qualifiers support']]],
  ['quat_20data_20as_20x_20y_20z_20w_20instead_20of_20w_20x_20y_20z_2',['quat data as x y z w instead of w x y z',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md38',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_21&quot;&gt;&lt;/a&gt; 2.21. GLM_FORCE_QUAT_DATA_XYZW: Force GLM to store quat data as x,y,z,w instead of w,x,y,z'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md577',1,'&lt;a class=&quot;anchor&quot; id=&quot;section2_21&quot;&gt;&lt;/a&gt; 2.21. GLM_FORCE_QUAT_DATA_XYZW: Force GLM to store quat data as x,y,z,w instead of w,x,y,z']]],
  ['quaternion_20functions_3',['Quaternion functions',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md132',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_11&quot;&gt;&lt;/a&gt; 3.11. Quaternion functions'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md671',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_11&quot;&gt;&lt;/a&gt; 3.11. Quaternion functions']]],
  ['quaternion_20types_4',['Quaternion types',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md126',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_9&quot;&gt;&lt;/a&gt; 3.9. Quaternion types'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md665',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_9&quot;&gt;&lt;/a&gt; 3.9. Quaternion types']]],
  ['quaternion_20types_20with_20precision_20qualifiers_5',['Quaternion types with precision qualifiers',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md129',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_10&quot;&gt;&lt;/a&gt; 3.10. Quaternion types with precision qualifiers'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md668',1,'&lt;a class=&quot;anchor&quot; id=&quot;section3_10&quot;&gt;&lt;/a&gt; 3.10. Quaternion types with precision qualifiers']]],
  ['questions_6',['questions',['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_externals_2_g_l_m_2manual.html#autotoc_md175',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_5&quot;&gt;&lt;/a&gt; 7.5. Where can I ask my questions?'],['../md__c_1_2_users_2_user_2_desktop_2_projects_2_multi_station_2_renderer3_d_d_s_2_externals_2_g_l_m_2manual.html#autotoc_md714',1,'&lt;a class=&quot;anchor&quot; id=&quot;section7_5&quot;&gt;&lt;/a&gt; 7.5. Where can I ask my questions?']]]
];
