#pragma once
#define IMGUI_IMPL_OPENGL_LOADER_CUSTOM
#include "../Source/ImGui/imconfig.h"
#include "../Source/ImGui/imgui.h"
#include "../Source/ImGui/imstb_textedit.h"
#include "../Source/ImGui/imstb_rectpack.h"
#include "../Source/ImGui/imgui_internal.h"
#include "../Source/ImGui/backends/imgui_impl_glfw.h"
#include "../Source/OpenGLBackendHelper.hpp"
