#ifndef IMAGEPROCESSING_MASK_H
#define IMAGEPROCESSING_MASK_H

#include "Core.hpp"

extern "C" {

	enum MaskType {
		LINE_DETECTION_VERTICAL,
		LINE_DETECTION_HORIZONTAL,
		LINE_DETECTION_LEFT_DIAGONAL,
		LINE_DETECTION_RIGHT_DIAGONAL,

		EDGE_DETECTION_PREWITT_VERTICAL,
		EDGE_DETECTION_PREWITT_HORIZONTAL,

		EDGE_DETECTION_SOBEL_VERTICAL,
		EDGE_DETECTION_SOBEL_HORIZONTAL , 

		EDGE_DETECTION_ROBINSON_N ,
		EDGE_DETECTION_ROBINSON_NW,
		EDGE_DETECTION_ROBINSON_W ,
		EDGE_DETECTION_ROBINSON_SW,
		EDGE_DETECTION_ROBINSON_S ,
		EDGE_DETECTION_ROBINSON_NE,
		EDGE_DETECTION_ROBINSON_E ,
		EDGE_DETECTION_ROBINSON_SE,

		EDGE_DETECTION_KIRSCH_N,
		EDGE_DETECTION_KIRSCH_NW,
		EDGE_DETECTION_KIRSCH_W,
		EDGE_DETECTION_KIRSCH_SW,
		EDGE_DETECTION_KIRSCH_S,
		EDGE_DETECTION_KIRSCH_NE,
		EDGE_DETECTION_KIRSCH_E,
		EDGE_DETECTION_KIRSCH_SE,

		EDGE_DETECTION_LAPLACE_POSITIVE,
		EDGE_DETECTION_LAPLACE_NEGATIVE,

		EDGE_DETECTION_ROBERTS_GX,
		EDGE_DETECTION_ROBERTS_GY,

		FILTER_LOW_PASS_SPATIAL,
		
		FILTER_HIGH_PASS_SPATIAL
	};

	struct MaskAttributes {
		uint32_t width;
		uint32_t height;
		void* mask;
		enum MaskType type;
	};

	struct LineDetectorMasks {
		float ver[3][3];
		float hor[3][3];
		float rdia[3][3];
		float ldia[3][3];
	};

	typedef bool (*MaskResolveFunc)(enum MaskType type, struct MaskAttributes* attrs);

	struct MaskAttributes* MaskGet(enum MaskType type );
};

#endif 
